[package]
name = "no_ptr"
version = "0.0.0"
authors = ["Richard Berry <rjsberry@pm.me>"]
edition = "2018"

[features]
default = []
pool = ["heapless"]

[dependencies]
heapless = { version = "^0.5.5", optional = true }

[dev-dependencies]
heapless = { version = "^0.5.5", features = ["x86-sync-pool"] }
