[package]
name = "no_alloc-san"
version = "0.0.0"
authors = ["Richard Berry <rjsberry@pm.me>"]
edition = "2018"

[dependencies.no_alloc]
path = ".."

[[bin]]
name = "box_s"
path = "box_s.rs"

[[bin]]
name = "box"
path = "box.rs"
